# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseturi',
            name='uri',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'ftp', 'ftps', b'file'])]),
        ),
        migrations.AlterUniqueTogether(
            name='dataseturi',
            unique_together=set([('uri', 'dataset')]),
        ),
    ]
