# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 13:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_populate_entry_id_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='entry_id',
            field=models.CharField(default=uuid.uuid4, max_length=80, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_.-]*$', b'Only alphanumeric characters are allowed.')]),
        ),
    ]
