# Generated by Django 2.2.2 on 2019-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190130_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataseturi',
            name='name',
            field=models.CharField(default='fileService', max_length=20),
        ),
        migrations.AddField(
            model_name='dataseturi',
            name='service',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
