# Generated by Django 2.1.5 on 2019-02-05 12:18

from django.db import migrations

def forward(apps, schema_editor):
    Dataset = apps.get_model('catalog', 'Dataset')
    DatasetParameter = apps.get_model('catalog', 'DatasetParameter')
    for ds in Dataset.objects.all():
        dataset_params = DatasetParameter.objects.filter(dataset=ds)
        for dp in dataset_params:
            ds.newparameters.add(dp.parameter)

def backward(apps, schema_editor):
    Dataset = apps.get_model('catalog', 'Dataset')
    DatasetParameter = apps.get_model('catalog', 'DatasetParameter')
    for ds in Dataset.objects.all():
        for pp in ds.newparameters.all():
            dp, created = DatasetParameter.objects.get_or_create(dataset=ds, parameter=pp)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008a_add_newparameters_field'),
    ]

    operations = [
            migrations.RunPython(forward, backward),
    ]
