# Generated by Django 2.1.5 on 2019-02-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
        ('catalog', '0008b_migrate_parameters_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='parameters',
        ),
    ]
