# Generated by Django 2.1.5 on 2019-02-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
        ('catalog', '0007c_remove_source_and_specs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='newparameters',
            field=models.ManyToManyField(to='vocabularies.Parameter'),
        ),
    ]
