# Generated by Django 2.1.5 on 2019-02-05 12:18

from django.db import migrations

def forward(apps, schema_editor):
    Dataset = apps.get_model('catalog', 'Dataset')
    for ds in Dataset.objects.all():
        ds.newparameters.add(ds.parameters.parameter)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008a_add_newparameters_field'),
    ]

    operations = [
            migrations.RunPython(forward, backward),
    ]
