# Generated by Django 3.0.6 on 2020-10-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_auto_20200331_0806'),
        ('catalog', '0008_auto_20200331_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='parameters',
            field=models.ManyToManyField(to='vocabularies.Parameter'),
        ),
        migrations.DeleteModel(
            name='DatasetParameter',
        ),
        migrations.AddField(
            model_name='dataset',
            name='parameters',
            field=models.ManyToManyField(to='vocabularies.Parameter'),
        ),
    ]
