# Generated by Django 2.1.5 on 2019-02-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190204_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='newparameters',
            new_name='parameters',
        ),
    ]
