# Generated by Django 3.0.6 on 2020-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_auto_20200331_0806'),
        ('catalog', '0008_auto_20200331_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetParameter',
        ),
    ]
