# Generated by Django 3.0 on 2021-05-25 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201019_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataseturi',
            name='uri',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'ftp', 'ftps', 'file'])]),
        ),
    ]
