# Generated by Django 3.2.25 on 2025-05-12 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import geospaas.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0006_auto_20250512_1411'),
        ('catalog', '0011_auto_20210525_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(validators=[geospaas.catalog.models.validate_tag])),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='keywords',
            field=models.ManyToManyField(to='vocabularies.Keyword'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
    ]
