# Generated by Django 3.2.25 on 2025-05-12 14:14

from django.db import migrations


def populate_location(apps, schema_editor):
    Dataset = apps.get_model("catalog", "dataset")
    for dataset in Dataset.objects.all():
        dataset.location = dataset.geographic_location.geometry
        dataset.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20250512_1411'),
    ]

    operations = [
        migrations.RunPython(populate_location, reverse_code=migrations.RunPython.noop),
    ]
