# Generated by Django 3.2.25 on 2025-05-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0007_auto_20250513_0616'),
        ('catalog', '0013_auto_20250512_1414'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='source',
            name='unique_source'),
        migrations.RemoveField(
            model_name='source',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='source',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='ISO_topic_category',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data_center',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='gcmd_location',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='geographic_location',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='source',
        ),
        migrations.DeleteModel(
            name='GeographicLocation',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
