# Generated by Django 3.2.25 on 2025-05-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20250513_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataseturi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dataseturi',
            name='service',
        ),
    ]
