# Generated by Django 3.2.25 on 2025-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20250515_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='data',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='legacy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='unique_tag'),
        ),
    ]
