"""
Django settings for geospaas_project project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'chu2p96if%&^09w6okqjwc-%+hmpc1t3@b&i8*+3nvdk!xpdb0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
# BEGIN ANSIBLE MANAGED BLOCK leaflet
'leaflet',
# END ANSIBLE MANAGED BLOCK leaflet
# BEGIN ANSIBLE MANAGED BLOCK django_forms_bootstrap
'django_forms_bootstrap',
# END ANSIBLE MANAGED BLOCK django_forms_bootstrap
# BEGIN ANSIBLE MANAGED BLOCK geospaas.viewer
'geospaas.viewer',
# END ANSIBLE MANAGED BLOCK geospaas.viewer
# BEGIN ANSIBLE MANAGED BLOCK geospaas.nansat_ingestor
'geospaas.nansat_ingestor',
# END ANSIBLE MANAGED BLOCK geospaas.nansat_ingestor
# BEGIN ANSIBLE MANAGED BLOCK geospaas.catalog
'geospaas.catalog',
# END ANSIBLE MANAGED BLOCK geospaas.catalog
# BEGIN ANSIBLE MANAGED BLOCK geospaas.vocabularies
'geospaas.vocabularies',
# END ANSIBLE MANAGED BLOCK geospaas.vocabularies
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tests.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tests.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
        'NAME': os.path.join(BASE_DIR, 'geodjango.db'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# BEGIN ANSIBLE MANAGED BLOCK
MEDIA_URL = '/site_media/media/'
STATIC_ROOT = "/vagrant/shared/icetype_vm/site_media/static"
MEDIA_ROOT =  "/vagrant/shared/icetype_vm/site_media/media/"
DOWNLOADS_ROOT = "/vagrant/shared/icetype_vm/site_media/downloads"
PRODUCTS_ROOT = "/vagrant/shared/icetype_vm/site_media/products"
STATICFILES_DIRS = [
"/vagrant/shared/icetype_vm/geospaas_project/static",
]
SERIALIZATION_MODULES = {"geojson": "django.contrib.gis.serializers.geojson",}
ALLOWED_HOSTS = ['*']
SPATIALITE_LIBRARY_PATH = 'mod_spatialite'
# END ANSIBLE MANAGED BLOCK
