# Generated by Django 2.0.6 on 2018-06-18 11:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField()),
                ('date0', models.DateField()),
                ('date1', models.DateField()),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('source', models.ManyToManyField(blank=True, to='catalog.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField()),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisualizationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.DatasetParameter')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Visualization')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('catalog.dataset',),
        ),
        migrations.AddField(
            model_name='visualization',
            name='ds_parameters',
            field=models.ManyToManyField(through='viewer.VisualizationParameter', to='catalog.DatasetParameter'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='geographic_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.GeographicLocation'),
        ),
    ]
