# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160705_1331'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='source',
        ),
        migrations.AddField(
            model_name='search',
            name='source',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Source'),
        ),
    ]
