# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20170508_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='source',
            field=models.ManyToManyField(to='catalog.Source'),
        ),
    ]
