# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20170508_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='source',
            field=models.ManyToManyField(blank=True, to='catalog.Source'),
        ),
    ]
