# Generated by Django 2.1.5 on 2019-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20170508_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
