# Generated by Django 2.1.5 on 2019-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
        ('viewer', '0005_auto_20190130_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='source',
        ),
        migrations.AddField(
            model_name='search',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='vocabularies.Instrument'),
        ),
        migrations.AddField(
            model_name='search',
            name='parameter',
            field=models.ManyToManyField(blank=True, to='vocabularies.Parameter'),
        ),
        migrations.AddField(
            model_name='search',
            name='platform',
            field=models.ManyToManyField(blank=True, to='vocabularies.Platform'),
        ),
    ]
