# Generated by Django 2.1.4 on 2019-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='long_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='long_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='units',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='platform',
            name='long_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='platform',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='term',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='variable_level_1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='variable_level_2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sciencekeyword',
            name='variable_level_3',
            field=models.CharField(max_length=80),
        ),
    ]
