# Generated by Django 2.2.4 on 2019-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0002_auto_20190101_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='short_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
