# Generated by Django 2.2 on 2020-03-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0003_auto_20190829_0847'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datacenter',
            constraint=models.UniqueConstraint(fields=('bucket_level0', 'bucket_level1', 'bucket_level2', 'bucket_level3', 'short_name', 'long_name', 'data_center_url'), name='unique_data_center'),
        ),
        migrations.AddConstraint(
            model_name='horizontaldataresolution',
            constraint=models.UniqueConstraint(fields=('range',), name='unique_horizontal_data_resolution'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('category', 'instrument_class', 'type', 'subtype', 'short_name', 'long_name'), name='unique_instrument'),
        ),
        migrations.AddConstraint(
            model_name='isotopiccategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_iso_topic_category'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('category', 'type', 'subregion1', 'subregion2', 'subregion3'), name='unique_location'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('standard_name', 'short_name', 'units', 'gcmd_science_keyword'), name='unique_parameter'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('category', 'series_entity', 'short_name', 'long_name'), name='unique_platform'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('bucket', 'short_name', 'long_name'), name='unique_project'),
        ),
        migrations.AddConstraint(
            model_name='sciencekeyword',
            constraint=models.UniqueConstraint(fields=('category', 'topic', 'term', 'variable_level_1', 'variable_level_2', 'variable_level_3', 'detailed_variable'), name='unique_science_keyword'),
        ),
        migrations.AddConstraint(
            model_name='temporaldataresolution',
            constraint=models.UniqueConstraint(fields=('range',), name='unique_temporal_data_resolution'),
        ),
        migrations.AddConstraint(
            model_name='verticaldataresolution',
            constraint=models.UniqueConstraint(fields=('range',), name='unique_vertical_data_resolution'),
        ),
    ]
