# Generated by Django 3.0 on 2021-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0004_auto_20200331_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='short_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
