# Generated by Django 3.2.25 on 2025-05-13 06:16

from django.db import migrations
from django.db import models


def populate_keywords(apps, schema_editor):
    '''Make new Keyword entries from old models and update datasets to
    use them
    '''
    keywords = [
        ('Platform', 'gcmd_platform', 'source__platform'),
        ('Instrument', 'gcmd_instrument', 'source__instrument'),
        ('ISOTopicCategory', 'iso19115_topic_category', 'ISO_topic_category'),
        ('DataCenter', 'gcmd_provider', 'data_center'),
        ('Location', 'gcmd_location', 'gcmd_location'),
        ('ScienceKeyword', 'gcmd_science_keyword', None),
        ('Project', 'gcmd_project', None),
        ('HorizontalDataResolution', 'gcmd_horizontalresolutionrange', None),
        ('VerticalDataResolution', 'gcmd_verticalresolutionrange', None),
        ('TemporalDataResolution', 'gcmd_temporalresolutionrange', None),
    ]
    Keyword = apps.get_model("vocabularies", "Keyword")
    Dataset = apps.get_model("catalog", "dataset")

    for model_name, vocabulary, dataset_field_name in keywords:
        model = apps.get_model("vocabularies", model_name)
        fields = [
            f.name 
            for f in model._meta.get_fields()
            if f.name != 'id' and not isinstance(f, models.ManyToOneRel)
        ]
        for k in model.objects.all():
            # Create new Keyword entry
            new_keyword, _ = Keyword.objects.get_or_create(
                version='legacy',
                type=vocabulary,
                data={
                    field_name: getattr(k, field_name)
                    for field_name in fields
                }
            )

            # Update Datasets which had a reference to the old keyword
            if dataset_field_name is not None:
                for dataset in Dataset.objects.filter(**{dataset_field_name: k.id}):
                    dataset.keywords.add(new_keyword)


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0006_auto_20250512_1411'),
        ('catalog', '0012_auto_20250512_1411')
    ]

    operations = [
        migrations.RunPython(populate_keywords, reverse_code=migrations.RunPython.noop),
    ]
