# Generated by Django 3.2.25 on 2025-05-13 10:20

from django.db import migrations, models
import geospaas.vocabularies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0007_auto_20250513_0616'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parameter',
            name='unique_parameter',
        ),
        migrations.AddField(
            model_name='parameter',
            name='data',
            field=models.JSONField(null=True, validators=[geospaas.vocabularies.models.validate_parameter]),
        ),
    ]
