# Generated by Django 3.2.25 on 2025-05-13 10:04

from django.db import migrations


def update_parameters(apps, schema_editor):
    '''Copy Parameters data from old fields to JSON field
    '''
    Parameter = apps.get_model("vocabularies", "Parameter")
    for parameter in Parameter.objects.all():
        parameter.data = {
            'standard_name': parameter.standard_name,
            'short_name': parameter.short_name,
            'units': parameter.units,
        }
        parameter.save()


class Migration(migrations.Migration):
    dependencies = [
        ('vocabularies', '0008_auto_20250513_1020'),
    ]

    operations = [
        migrations.RunPython(update_parameters, reverse_code=migrations.RunPython.noop),
    ]
