# Generated by Django 3.2.25 on 2025-05-13 10:21

from django.db import migrations, models
import geospaas.vocabularies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0009_auto_20250513_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='data',
            field=models.JSONField(unique=True, validators=[geospaas.vocabularies.models.validate_parameter]),
        ),
    ]
