# Generated by Django 3.2.25 on 2025-05-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20250513_1302'),
        ('vocabularies', '0010_auto_20250513_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCenter',
        ),
        migrations.DeleteModel(
            name='HorizontalDataResolution',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='ISOTopicCategory',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ScienceKeyword',
        ),
        migrations.DeleteModel(
            name='TemporalDataResolution',
        ),
        migrations.DeleteModel(
            name='VerticalDataResolution',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='standard_name',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='units',
        ),
    ]
