# Generated by Django 3.2.25 on 2025-05-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0011_auto_20250513_1302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='type',
            new_name='kind',
        ),
        migrations.AddField(
            model_name='parameter',
            name='kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('version', 'kind', 'data'), name='unique_keyword'),
        ),
    ]
