# Generated by Django 3.2.25 on 2025-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0012_auto_20250514_0542'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('version', 'kind', 'data'), name='unique_parameter'),
        ),
    ]
