# Generated by Django 3.2.25 on 2025-05-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0013_parameter_unique_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-version', 'kind', 'data']},
        ),
    ]
