# Generated by Django 3.2.25 on 2025-12-01 06:54

from django.db import migrations, models
import geospaas.vocabularies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0014_alter_keyword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='data',
            field=models.JSONField(validators=[geospaas.vocabularies.models.validate_parameter]),
        ),
    ]
