# Generated by Django 3.0 on 2020-05-07 08:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_auto_20200331_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField()),
                ('date0', models.DateField()),
                ('date1', models.DateField()),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('source', models.ManyToManyField(blank=True, to='catalog.Source')),
            ],
        ),
    ]
