---
sudo: required

services:
  - docker

language: python
python: "2.7"

addons:
  apt:
    packages:
      - python-pip

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=archlinux_latest
  - OS=centos_7
  - OS=fedora_23
  - OS=fedora_24
  - OS=fedora_25
  - OS=fedora_26
  - OS=fedora_27
  - OS=fedora_28
  - OS=debian_jessie
  - OS=debian_stretch
  - OS=ubuntu_trusty
  - OS=ubuntu_xenial
  - OS=ubuntu_bionic
    
before_install:
  - pip install ansible-galaxy-local-deps dcb==0.0.14
  - ansible-galaxy-local-deps-write

script:
  - >-
    dcb
    --upstreamgroup andrewrothstein
    --upstreamapp ansible-anaconda
    --snippet from.j2 ansible-test-role.j2
    --pull ${OS}
    --write ${OS}
    --build ${OS}
    --push ${OS}
  - >-
    dcb
    --upstreamgroup andrewrothstein
    --upstreamapp ansible-miniconda
    --targetapp ansible-conda-env-miniconda
    --snippet from.j2 ansible-test-role.j2
    --write ${OS}
    --build ${OS}
    --push ${OS}
