---
galaxy_info:
  author: Andrew Rothstein
  description: creates a conda environment from an environment.yml
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - python
    - anaconda
    - conda

dependencies: []
  
