# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_level0', models.CharField(max_length=200)),
                ('bucket_level1', models.CharField(max_length=200)),
                ('bucket_level2', models.CharField(max_length=200)),
                ('bucket_level3', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=200)),
                ('data_center_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalDataResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('instrument_class', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ISOTopicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('subregion1', models.CharField(max_length=50)),
                ('subregion2', models.CharField(max_length=50)),
                ('subregion3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=30)),
                ('units', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('series_entity', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=6)),
                ('short_name', models.CharField(max_length=80)),
                ('long_name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('variable_level_1', models.CharField(max_length=30)),
                ('variable_level_2', models.CharField(max_length=30)),
                ('variable_level_3', models.CharField(max_length=30)),
                ('detailed_variable', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalDataResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalDataResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=220)),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='gcmd_science_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabularies.ScienceKeyword'),
        ),
    ]
