# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date0',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='date1',
            field=models.DateTimeField(),
        ),
    ]
