# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20160508_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date0',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='date1',
            field=models.DateField(),
        ),
    ]
