---
galaxy_info:
  author: Andrew Rothstein
  description: installs bash
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - development

dependencies: []
