# Generated by Django 2.0.6 on 2018-06-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('catalog.dataset',),
        ),
    ]
