channels:
  - conda-forge
dependencies:
  - python==3.11
  - django==3.2
  - gdal
  - ipykernel
  - nbconvert
  - netCDF4
  - pandoc
  - pythesint
  - python-dateutil
  - recommonmark
  - sphinx_rtd_theme
  - sphinx-autobuild
  - sphinx>=1.4
  - pip:
    - nansat
    - nbsphinx
