channels:
  - conda-forge
dependencies:
  - django==3.2
  - sphinx>=1.4
  - sphinx-autobuild
  - sphinx_rtd_theme
  - recommonmark
  - pandoc
  - nbconvert
  - ipykernel
  - python-dateutil
  - pip:
    - nbsphinx

