galaxy_info:
  author: Anton Korosov
  description: Init Django project for Geo-SPaaS
  company: NERSC
  license: GPLv3
  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - trusty

  galaxy_tags:
  - python
  - geodjango
  - geospaas

dependencies:
  - role: andrewrothstein.miniconda
    version: v5.1.5
    miniconda_escalate: no
    miniconda_parent_dir: '{{ django_conda_dir | dirname }}'
    miniconda_make_sys_default: yes

  - role: andrewrothstein.conda-env
    conda_env_name: '{{ django_env_name }}'
    conda_env_environment: conda_env_requirements.yml
    conda_env_escalate: no
    conda_env_conda_dir: '{{ django_conda_dir }}'


